/**
 * КОНФИГ КАТАЛОГА КУРСОВ
 * ------------------------------------------------------------
 * Чтобы добавить курс — допишите объект в массив courses (ниже).
 * Чтобы добавить категорию — допишите её в categories и укажите
 * ключ в categoryOrder (порядок в этом массиве = порядок на сайте).
 *
 * Поля курса:
 *   id       — уникальный идентификатор (латиница, без пробелов)
 *   code     — код курса, напр. "CS161"
 *   title    — полное название курса
 *   org      — университет / источник
 *   level    — уровень, напр. "Начальный", "Средний", "Продвинутый"
 *   category — ключ категории из объекта categories
 *   url      — прямая ссылка на курс
 * ------------------------------------------------------------
 */

window.CATALOG_CONFIG = {
  categoryOrder: [
    "programming",
    "algorithms",
    "systems",
    "os",
    "databases",
    "networks",
    "distributed",
    "ml",
    "math",
    "security",
    "aieng",
    "meta",
  ],

  categories: {
    programming: { name: "Основы программирования", color: "#4A7A96" },
    algorithms: { name: "Алгоритмы и структуры данных", color: "#B9893F" },
    systems: { name: "Системы и архитектура", color: "#A15C38" },
    databases: { name: "Базы данных", color: "#3E7C74" },
    networks: { name: "Сети", color: "#6B5B95" },
    ml: { name: "Машинное обучение и AI", color: "#A23B3B" },
    security: { name: "Кибербезопасность", color: "#45516B" },
    aieng: { name: "AI-инженерия и Software Eng", color: "#6E7F4F" },
    os: { name: "Операционные системы", color: "#5C8A8A" },
    distributed: { name: "Распределённые системы", color: "#8B5E3C" },
    math: { name: "Математика", color: "#7B68AE" },
    meta: { name: "Курируемые программы", color: "#8C7A5C" },
  },

  courses: [
    {
      id: "cs50",
      code: "CS50",
      title: "Введение в информатику",
      org: "Harvard",
      level: "Начальный",
      category: "programming",
      url: "https://cs50.harvard.edu/x/",
    },
    {
      id: "cs106a",
      code: "CS106A",
      title: "Programming Methodology",
      org: "Stanford",
      level: "Начальный",
      category: "programming",
      url: "https://cs106a.stanford.edu/",
    },
    {
      id: "cs61a",
      code: "CS61A",
      title: "Structure and Interpretation of Computer Programs",
      org: "UC Berkeley",
      level: "Начальный–средний",
      category: "programming",
      url: "https://cs61a.org/",
    },

    {
      id: "cs61b",
      code: "CS61B",
      title: "Data Structures",
      org: "UC Berkeley",
      level: "Средний",
      category: "algorithms",
      url: "https://sp26.datastructur.es/",
    },
    {
      id: "mit6006",
      code: "6.006",
      title: "Introduction to Algorithms",
      org: "MIT",
      level: "Средний",
      category: "algorithms",
      url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/",
    },

    {
      id: "cs61c",
      code: "CS61C",
      title: "Great Ideas in Computer Architecture",
      org: "UC Berkeley",
      level: "Средний",
      category: "systems",
      url: "https://inst.eecs.berkeley.edu/~cs61c/",
    },
    {
      id: "mit6002",
      code: "6.002",
      title: "Circuits and Electronics",
      org: "MIT",
      level: "Средний",
      category: "systems",
      url: "https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/",
    },
    {
      id: "mit601sc",
      code: "6.01SC",
      title: "Introduction to EE & CS",
      org: "MIT",
      level: "Начальный–средний",
      category: "systems",
      url: "https://ocw.mit.edu/courses/6-01sc-introduction-to-electrical-engineering-and-computer-science-i-spring-2011/",
    },

    {
      id: "cmu15445",
      code: "15-445",
      title: "Database Systems",
      org: "CMU",
      level: "Продвинутый",
      category: "databases",
      url: "https://15445.courses.cs.cmu.edu/",
    },

    {
      id: "cs144",
      code: "CS144",
      title: "Introduction to Computer Networking",
      org: "Stanford",
      level: "Продвинутый",
      category: "networks",
      url: "https://cs144.github.io/",
    },

    {
      id: "cs229",
      code: "CS229",
      title: "Machine Learning",
      org: "Stanford",
      level: "Продвинутый",
      category: "ml",
      url: "https://cs229.stanford.edu/",
    },
    {
      id: "cs231n",
      code: "CS231n",
      title: "Deep Learning for Computer Vision",
      org: "Stanford",
      level: "Продвинутый",
      category: "ml",
      url: "https://cs231n.stanford.edu/",
    },
    {
      id: "cs188",
      code: "CS188",
      title: "Introduction to Artificial Intelligence",
      org: "UC Berkeley",
      level: "Средний–продвинутый",
      category: "ml",
      url: "https://inst.eecs.berkeley.edu/~cs188/",
    },
    {
      id: "fastai",
      code: "fast.ai",
      title: "Practical Deep Learning for Coders",
      org: "fast.ai / USF",
      level: "Средний",
      category: "ml",
      url: "https://course.fast.ai/",
    },

    {
      id: "mit6858",
      code: "6.858",
      title: "Computer Systems Security",
      org: "MIT",
      level: "Продвинутый",
      category: "security",
      url: "https://ocw.mit.edu/courses/6-858-computer-systems-security-fall-2014/",
    },

    {
      id: "cs146s",
      code: "CS146S",
      title: "The Modern Software Developer",
      org: "Stanford",
      level: "Продвинутый",
      category: "aieng",
      url: "https://github.com/mihail911/modern-software-dev-assignments",
    },

    {
      id: "ossu",
      code: "OSSU",
      title: "Полный учебный план по Computer Science",
      org: "Open Source Society University",
      level: "Все уровни",
      category: "meta",
      url: "https://github.com/ossu/computer-science",
    },
    {
      id: "tenfoundation",
      code: "Тен Фонд",
      title: "База программиста",
      org: "Влад Тен / @tenfoundation",
      level: "Все уровни",
      category: "meta",
      url: "https://youtu.be/fW_imcrTA_c?si=KU0S22DZzgvLN9Dd",
    },
    {
      id: "comp-sys-yt",
      code: "Computer Systems",
      title: "Computer Systems (видеолекции)",
      org: "YouTube",
      level: "Средний",
      category: "systems",
      url: "https://www.youtube.com/watch?v=Keducx5bp-g&list=PL0j-r-omG7i0-mnsxN5T4UcVS1Di0isqf&index=17",
    },
    {
      id: "nand2tetris",
      code: "Nand2Tetris",
      title: "From Nand to Tetris",
      org: "nand2tetris.org",
      level: "Средний",
      category: "systems",
      url: "https://www.nand2tetris.org",
    },
    {
      id: "ostep",
      code: "OSTEP",
      title: "Operating Systems: Three Easy Pieces",
      org: "UW-Madison / Remzi Arpaci-Dusseau",
      level: "Средний",
      category: "os",
      url: "https://pages.cs.wisc.edu/~remzi/OSTEP/",
    },
    {
      id: "cs537",
      code: "CS 537",
      title: "Operating Systems",
      org: "UW-Madison",
      level: "Продвинутый",
      category: "os",
      url: "https://pages.cs.wisc.edu/~remzi/Classes/537/Fall2021/",
    },
    {
      id: "mit6s081",
      code: "6.S081",
      title: "Operating System Engineering",
      org: "MIT",
      level: "Продвинутый",
      category: "os",
      url: "https://pdos.csail.mit.edu/6.S081/2021/schedule.html",
    },
    {
      id: "mit-algo-yt",
      code: "MIT 6.006",
      title: "Introduction to Algorithms (видеолекции)",
      org: "MIT / YouTube",
      level: "Средний",
      category: "algorithms",
      url: "https://www.youtube.com/watch?v=oFVYVzlvk9c&list=PLUl4u3cNGP63EdVPNLG3ToM6LaEUuStEY&index=13",
    },
    {
      id: "3b1b",
      code: "3Blue1Brown",
      title: "Математика (визуальные лекции)",
      org: "3Blue1Brown",
      level: "Все уровни",
      category: "math",
      url: "https://www.3blue1brown.com/#lessons",
    },
    {
      id: "mit-ocw-math",
      code: "MIT OCW Math",
      title: "Курсы математики",
      org: "MIT OpenCourseWare",
      level: "Все уровни",
      category: "math",
      url: "https://ocw.mit.edu/course-lists/scholar-courses/",
    },
    {
      id: "khanacademy",
      code: "Khan Academy",
      title: "Математика",
      org: "Khan Academy",
      level: "Начальный",
      category: "math",
      url: "https://www.khanacademy.org",
    },
    {
      id: "mathacademy",
      code: "Math Academy",
      title: "Математика для взрослых",
      org: "Math Academy",
      level: "Все уровни",
      category: "math",
      url: "https://mathacademy.com/adult-students",
    },
    {
      id: "wireshark",
      code: "Wireshark Labs",
      title: "Лабораторные по сетям (Wireshark)",
      org: "UMass / Kurose & Ross",
      level: "Средний",
      category: "networks",
      url: "http://gaia.cs.umass.edu/kurose_ross/wireshark.php",
    },
    {
      id: "cmu15445-fall2024",
      code: "15-445",
      title: "Database Systems (assignments)",
      org: "CMU",
      level: "Продвинутый",
      category: "databases",
      url: "https://15445.courses.cs.cmu.edu/fall2024/assignments.html",
    },
    {
      id: "db-yt",
      code: "DB Systems",
      title: "Database Systems (видеолекции)",
      org: "YouTube",
      level: "Средний",
      category: "databases",
      url: "https://www.youtube.com/watch?v=niLwbfE3V9Q&list=PLSE8ODhjZXjYDBpQnSymaectKjxCy6BYq&index=20",
    },
    {
      id: "mit6824",
      code: "6.824",
      title: "Distributed Systems",
      org: "MIT",
      level: "Продвинутый",
      category: "distributed",
      url: "https://pdos.csail.mit.edu/6.824/schedule.html",
    },
    {
      id: "dist-yt",
      code: "Distributed Systems",
      title: "Распределённые системы (видеолекции)",
      org: "YouTube",
      level: "Средний",
      category: "distributed",
      url: "https://www.youtube.com/watch?v=UEAMfLPZZhE&list=PLeKd45zvjcDFUEv_ohr_HdUFe97RItdiB",
    },
    {
      id: "pwncollege",
      code: "pwn.college",
      title: "Cybersecurity",
      org: "pwn.college",
      level: "Все уровни",
      category: "security",
      url: "https://pwn.college/",
    },
    {
      id: "cs253",
      code: "CS 253",
      title: "Web Security",
      org: "Stanford",
      level: "Продвинутый",
      category: "security",
      url: "https://web.stanford.edu/class/cs253/",
    },
    {
      id: "mit61600",
      code: "6.1600",
      title: "Applied Cryptography",
      org: "MIT",
      level: "Продвинутый",
      category: "security",
      url: "https://61600.csail.mit.edu/2023/",
    },
  ],
};
